### ISSUE TITLE
Add One Click Stake All NFTs

### ISSUE THREAD

**Issue by monstadao** [cardinal-labs/cardinal-staking-ui#101]
Hi Team
This is a simple feature that allows the holder to stake all their Allowed NFTs into a live pool.
Some benefit of "One Click Stake NFTs"  is saving holders time, especially hold more than 20 NFTs
![unknown](https://user-images.githubusercontent.com/104182525/179198511-2c13a1b6-8e45-474c-9237-c89a9584896c.png)

**Comment by jpbogle** [comment]
Thanks for submitting here! 

This was the commit to add claim all FYI https://github.com/cardinal-labs/cardinal-staking-ui/commit/bcc9f8718192fd91c26883f2d5ea70d2c66d03da

PR Opened here https://github.com/cardinal-labs/cardinal-staking-ui/pull/102
