### ISSUE TITLE
Hostname mapping does not support mapping `/`

### ISSUE THREAD

**Issue by jpbogle** [cardinal-labs/cardinal-staking-ui#107]
See PR for more details https://github.com/cardinal-labs/cardinal-staking-ui/pull/106

>Unfortunately it has 2 shortcomings which is the domain HAS to add your pools name on the path, it will not allow for rewriting / so there is both a rewrite and redirect rule added. In addition nextJS support for importing a ESM module into next.config.js does not work so right now you have to take 1 extra step to define the hostname mapping. Eventually we will figure out a way to have all pool config in one place

This issue is to track support mapping from `/` without a name in the path as well as consolidating the config objects

**Comment by gchatz22** [comment]
Resolved with this PR https://github.com/cardinal-labs/cardinal-staking-ui/pull/181

Changed the way we handle custom hostnames registering domains on vercel and handling mapping the subdomain to the correct hostname with a global `StakePoolMetadataProvider`
