### ISSUE TITLE
Show staked NFTS country wise

### ISSUE THREAD

**Issue by johgear** [cardinal-labs/cardinal-staking-ui#91]
My NFT collection has the following metadata
Name: Jango #1 
Background: Blue:
Country: Atlanta
Position: Horizontal.

The collection is about 5000. 
Out of these 
1000 NFTs belong to country Atlanta,
1000 NFTs Georgia
1000 NFTs Tennsse
1000 NFTs California

My requirement is to show on the Cardinal UI, the percentage staked by countries and also hyperlink the country name ( to redirect to a third-party website )  I have shared with you a screenshot of what exactly I'm looking for. To make this happens pls let me know how to implement this on your code. 

![White with Pink Hearts Doodle Girlfriend Valentines Card](https://user-images.githubusercontent.com/11072847/177056896-00ab61ac-f1f0-43ba-bf9d-6f940d81512e.png)

**Comment by triiq** [comment]
hey! if you still need help with this I'm happy to help make it happen :)

**Comment by johgear** [comment]
yes needed @triiq

**Comment by triiq** [comment]
Awesome @johgear add me on discord triiq#0001 or Twitter @triiq_

**Comment by johgear** [comment]
Demo NFTs uploaded 
On devnet
Pool ID FMTG6KBy4xMPRZZ6vD611oEKCdqqrW7z5VuebBusuRzt
Collection address DSW8CMHrCxXUo3b4uvJEZtMtVTjJ5VSV5Hk8ZKVbeReB

**Comment by gchatz22** [comment]
Hey, added logic https://github.com/cardinal-labs/cardinal-staking-ui/commit/468e83aa56425c8b5943abaf7d94ef221d584873 with which you can specify what analytics you want to display in your stake pool in the [mapping file](https://github.com/cardinal-labs/cardinal-staking-ui/commit/468e83aa56425c8b5943abaf7d94ef221d584873#diff-b1f8421db620e694d8283aba8e734aba8b0f8db4db6347da20be698ae4c735a8R14), and are displayed at the top of the pool. Currently the one supported is `metadata` analytics for `staked` tokens in which you can specify what metadata key you want to show analytics for aka <img width="1512" alt="Screen Shot 2022-07-15 at 2 02 12 PM" src="https://user-images.githubusercontent.com/44476526/179210944-930377d6-315d-48e7-959c-76352c49d86d.png">

Let me know if this what's desired and can change accordingly

**Comment by johgear** [comment]
worked well. great serr. Thank you. 
 I put down how i have mentioned in the api mapping to get the desired result. Just check pls
Two things
1. Only 3 countries showing, I had actually put 4.
2. Anyway these can be hyperlinked? Countries should be clickable which redirects to another website, for which i'll provide the url there. 

Attached the result 
<img width="1417" alt="Screenshot 2022-07-15 at 6 36 16 PM" src="https://user-images.githubusercontent.com/11072847/179229115-643a6272-1933-4afe-a44a-6b5e93b152c9.png">


{
    name: 'animals',
    displayName: 'Animals',
    stakePoolAddress: new PublicKey(
      'FMTG6KBy4xMPRZZ6vD611oEKCdqqrW7z5VuebBusuRzt'
    ),
    imageUrl: '/logo-colored.png',
    colors: {
      primary: 'rgb(10,50,38,0.9)',
      secondary: 'rgb(157,120,138, 0.6)',
    },
    analytics: [
      {
        metadata: {key: 'Country' , type:'staked'}
      }
    ],
  },

**Comment by johgear** [comment]
No. 4 of them shown. Not sure why it was not showing 4 earlier. Just the 2 feature mentioned above to be noted. 

<img width="1250" alt="Screenshot 2022-07-15 at 6 48 25 PM" src="https://user-images.githubusercontent.com/11072847/179231014-bf0a4eb7-2270-4013-8cf3-709b0682498b.png">

**Comment by gchatz22** [comment]
Okay I see, are the hyperlinks you envision on the same format aka say `https://some-domain.com/{countryName}` or different for each country

**Comment by johgear** [comment]
different for each country.

**Comment by johgear** [comment]
Also, the math has to be adjusted it seems. Ideally, if 100% staked then all country's values should also be 100% staked.
In this collection total Atlanta, California, Georgia, and Tennesse are 3,4,8,5. 

Now % staked showing as as below 
<img width="1252" alt="Screenshot 2022-07-16 at 10 13 14 AM" src="https://user-images.githubusercontent.com/11072847/179340015-15606b19-c778-46be-8394-bcd8cd748dbd.png">

**Comment by jpbogle** [comment]
are you saying the percentage is not out of the total - but instead out of the total just for that attribute?

**Comment by johgear** [comment]
out of the total just fot that attribute/grouping. 
You can refer https://suteki.stakooor.app/ staking platform. thay have a similar one what we are thinking

**Comment by johgear** [comment]
yes. percentage shown is not out of the total. Atlanta should be 100% since all the NFTS in that collection are staked. Not just Atlanta but california, Tennesse, Georgia also. Hope you are able to understand. Wish we could discuss over a call or so to explain furthur. Thanks.

**Comment by gchatz22** [comment]
Okay I believe we can support the latter piece, the out of the total per country, and not total of all NFTs. The different hyperlinks I believe would be a bit too hard to generalize in a broad rule specified for metadata stats though. I don't think we would support that. Most definitely though with a fork of our UI adding your customizations to support the hyperlinks, it would work.

**Comment by johgear** [comment]
wokay hyperlink part is a bit tricky. let's just do the math part. that should do.

**Comment by gchatz22** [comment]
Hey made this feature possible in our UI, by defining an analytics object in the mapping file such that
```
analytics: [
      {
        metadata: {
          key: 'Country',
          type: 'staked',
          totals: [
            {
              key: 'Atlanta',
              value: 1000, // eg. total number of Atlanta tokens
            },
            {
              key: 'California',
              value: 900, // eg. total number of California tokens
            },
            {
              key: 'Tennessee',
              value: 800, // eg. total number of Tennessee tokens
            },
            {
              key: 'Georgia',
              value: 700, // eg. total number of Georgia tokens
            },
          ],
        },
      },
    ],
```

Let me us know what you think and if there is any confusion with it

**Comment by johgear** [comment]
analytics: [
      {
        metadata: {
          key: 'Country',
          type: 'staked',
          totals: [
            {
              key: 'Atlanta',
              value: 3,
            },
            {
              key: 'California',
              value: 4, 
            },
            {
              key: 'Tennessee',
              value: 8, 
            },
            {
              key: 'Georgia',
              value: 5,
            },
          ],
        },
      },
    ],
    maxStaked: 20,
  },

So I added the as per your instructions but I'm getting a different percentage value. here's the screenshot. Do I have to update anything?
<img width="1275" alt="Screenshot 2022-08-03 at 1 22 01 PM" src="https://user-images.githubusercontent.com/11072847/182554231-cfb24f17-dfb4-40f3-ba88-0d811997d5d1.png">

**Comment by gchatz22** [comment]
There was a division on the UI side that would still divide by the `maxStaked` number configured. https://github.com/cardinal-labs/cardinal-staking-ui/commit/f5b321e164c67194591eb1e5808e6f49a8e91025#diff-997911902d972e73aac70e0bdc4d1b7bd38a7c5ff790f08e8af3357a94a2bfaeR813.

Also for what is worth in your config above^^, seems like in the metadata of the mints, `Tennessee` is misspelled to `Tennesse` haha. Also seems like `Georgia` value should be 8 and `Tennessee` value should be 5.

**Comment by johgear** [comment]
Ayoo. I mispelt Tennessee. thanks for pointing it out. I adjusted the values. Removed maxstaked. But still math is not doing right. Check the screenshot. 
<img width="1284" alt="Screenshot 2022-08-04 at 1 02 13 PM" src="https://user-images.githubusercontent.com/11072847/182790027-b48358af-456a-4b5b-9438-f811cf253d3b.png">

**Comment by jpbogle** [comment]
@johgear looks like @gchatz22 addressed this mostly with https://github.com/cardinal-labs/cardinal-staking-ui/commit/468e83aa56425c8b5943abaf7d94ef221d584873

and then a few follow-ups on discord and finally this to ensure it reloads without refreshing the page https://github.com/cardinal-labs/cardinal-staking-ui/commit/1c0e33a7f50651555f2e71070c1ba4c513ad731b

Thanks for suggesting this feature and glad we could work through it with you! Closing issue now

**Comment by johgear** [comment]
Thank you Cardinal labs and @gchatz22
